- repository: yukke42/ros2-project-template
  files:
    - source: .github/workflows/build-and-test-differential.yaml
    - source: .github/workflows/build-and-test.yaml
    - source: .github/workflows/cancel-previous-workflows.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .github/dependabot.yaml
    - source: .clang-format
    - source: .editorconfig
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .pre-commit-config.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: pyproject.toml
    - source: setup.cfg
